[[moreau_cpu]]
arch = "x86_64"
git-tree-sha1 = "cf1474f3244fc5639c792069149f3d19d70df6ef"
libc = "glibc"
os = "linux"

    [[moreau_cpu.download]]
    sha256 = "72ae17f2220bedfb6eb9e4aa61e3f2ac71df5038e5ec127fd1606bf8f93655a8"
    url = "https://github.com/optimalintellect/Moreau_CPU_jll.jl/releases/download/v0.3.2/moreau-cpu-linux-x86_64.tar.gz"
[[moreau_cpu]]
arch = "aarch64"
git-tree-sha1 = "5cef70b058139e65cc3b13839acd3fa120a35605"
os = "macos"

    [[moreau_cpu.download]]
    sha256 = "c6d44b33f817f476af6dcca47f130e9f4fed72332af1e84fc1e2d100431ec71e"
    url = "https://github.com/optimalintellect/Moreau_CPU_jll.jl/releases/download/v0.3.2/moreau-cpu-macos-arm64.tar.gz"
